### ISSUE TITLE
APP起動ブラウザ画面

### ISSUE THREAD

**Issue by koma236** [sakinemoto/RaisetechAWS#3]
<img width="1149" alt="スクリーンショット 2023-04-24 7 14 45" src="https://user-images.githubusercontent.com/88425419/233868990-9a202ae6-31b3-4b86-bc5f-9dd35ecd7ead.png">

**Comment by koma236** [comment]
<img width="1353" alt="スクリーンショット 2023-04-24 7 21 05" src="https://user-images.githubusercontent.com/88425419/233869369-24db921e-35f8-4f16-8cd2-b33cd9a88989.png">

**Comment by sakinemoto** [comment]
<img width="463" alt="スクリーンショット 2023-04-28 6 17 09" src="https://user-images.githubusercontent.com/88425419/234997184-7717d157-f33b-491f-92a5-7b1501457361.png">

**Comment by koma236** [comment]
<img width="443" alt="スクリーンショット 2023-04-28 6 46 21" src="https://user-images.githubusercontent.com/88425419/234998197-1cd5f2b6-8c14-42f1-aa3c-accc49662008.png">

**Comment by sakinemoto** [comment]
<img width="1360" alt="スクリーンショット 2023-04-28 6 46 54" src="https://user-images.githubusercontent.com/88425419/234998287-bd9b8e07-149a-438c-be0f-103bf740a560.png">

**Comment by koma236** [comment]
<img width="643" alt="スクリーンショット 2023-04-28 6 52 59" src="https://user-images.githubusercontent.com/88425419/234999293-623555f0-aab3-4f76-bd29-b9a96a73d94a.png">

**Comment by sakinemoto** [comment]
<img width="2102" alt="VPC作成" src="https://github.com/sakinemoto/RaisetechAWS/assets/88425419/65d715bc-7259-4b6b-ab42-661a3787837a">

**Comment by sakinemoto** [comment]
<img width="2102" alt="EC2インスタンス作成" src="https://github.com/sakinemoto/RaisetechAWS/assets/88425419/ef908b42-a903-4894-879c-0edb87d1094b">

**Comment by koma236** [comment]
<img width="2067" alt="VPC作成" src="https://github.com/sakinemoto/RaisetechAWS/assets/88425419/b272db50-48ab-440f-86c0-54c8e592257a">

**Comment by koma236** [comment]
<img width="2067" alt="EC2インスタンス作成" src="https://github.com/sakinemoto/RaisetechAWS/assets/88425419/ed72704a-3dc3-4547-a7d0-9112a4507e31">

**Comment by koma236** [comment]
<img width="1256" alt="EC2からssh接続" src="https://github.com/sakinemoto/RaisetechAWS/assets/88425419/3b5a1b35-c049-42bd-a67e-c96f9c4eb9ec">

**Comment by koma236** [comment]
<img width="2101" alt="RDS作成1" src="https://github.com/sakinemoto/RaisetechAWS/assets/88425419/4beee966-5b04-4b27-b2b0-32c28a3684bf">
<img width="2108" alt="RDS作成２" src="https://github.com/sakinemoto/RaisetechAWS/assets/88425419/621772a4-641d-4c2e-9d54-4b55668f0ea9">
<img width="1256" alt="RDS接続" src="https://github.com/sakinemoto/RaisetechAWS/assets/88425419/d81b6cf2-2a2d-42a3-b274-80e0845d895b">

**Comment by koma236** [comment]
<img width="1256" alt="mysqlの事前準備" src="https://github.com/sakinemoto/RaisetechAWS/assets/88425419/8112834b-41c4-43a9-a9ac-becafd58ed3f">

**Comment by koma236** [comment]
<img width="1253" alt="pumaで起動" src="https://github.com/sakinemoto/RaisetechAWS/assets/88425419/8fcb1e3e-9765-4e29-88c4-42097fe77070">

**Comment by koma236** [comment]
<img width="1699" alt="create" src="https://github.com/sakinemoto/RaisetechAWS/assets/88425419/5f8c2409-1401-431c-a30d-88688b926b1e">

**Comment by koma236** [comment]
<img width="1431" alt="delete" src="https://github.com/sakinemoto/RaisetechAWS/assets/88425419/aca12ba2-6b06-4a02-bdd7-f8f6b3a6ee61">

**Comment by koma236** [comment]
<img width="1244" alt="nginxunicorn_起動" src="https://github.com/sakinemoto/RaisetechAWS/assets/88425419/d5fe882c-fd43-42d8-b8ff-95ece3233eb6">

**Comment by koma236** [comment]
<img width="1604" alt="スクリーンショット 2023-08-14 13 51 44" src="https://github.com/sakinemoto/RaisetechAWS/assets/88425419/312a08cb-7c6b-428d-b82c-50b60ced4162">

**Comment by koma236** [comment]
![lecture05](https://github.com/sakinemoto/RaisetechAWS/assets/88425419/28d5caff-7241-4305-931d-2385984cfff6)

**Comment by koma236** [comment]
<img width="1424" alt="healthcheck" src="https://github.com/sakinemoto/RaisetechAWS/assets/88425419/f89dc0e8-a517-4706-b21f-b50066e9dbc9">

**Comment by koma236** [comment]
<img width="1259" alt="bucket" src="https://github.com/sakinemoto/RaisetechAWS/assets/88425419/fcdd0aa4-c252-4fd9-a62a-f15ab3f4dff7">
